### ISSUE TITLE
should pch and lty vary by group?

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#27]

**Comment by vincentarelbundock** [comment]
Personally, I think it would be a bad idea to have them vary automatically. Groups should be identified by one aesthetic dimension whenever possible. Otherwise the plot becomes very distracting.

However I do think it's about important to offer a simple way to change the aesthetic that varies. But we can already do that by setting col=1 and pch=1:ngrp. 

This should probably be documented prominently.

**Comment by grantmcdermott** [comment]
Thanks @vincentarelbundock. Totally agree that these shouldn't vary by default. (The issue title isn't clear; my bad.) I was thinking instead of offering a convenience way for users to opt into this. I have a PR incoming shortly that I'll tag you as a reviewer for to look at.
