### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/plot2#4]
- [x] #16
- [x] "col" argument could be smarter (e.g., inherit from by) [Closing b/c I think we have a better solution with #5 now.]
- [x] #27
- [x] #26
- [x] #17
- [x] #65

**Comment by zeileis** [comment]
Regarding the last question: I think it's fine if pch does not vary by group by default. But it would be nice to support something like `plot(y ~ x | z, pch = c(1, 2))` if `z` is a factor with two groups. Similarly, `col = c(3, 5)` if you want other colors than the first two from the current `palette`.

Example: It would be nice if the `plot2()` below would yield the same kind of plot as the `plot()`.

```
data("whiteside", package = "MASS")
plot(Gas ~ Temp, data = whiteside, col = palette.colors()[2:3][Insul], pch = c(19, 17)[Insul])
plot2(Gas ~ Temp | Insul, data = whiteside, col = 2:3, pch = c(19, 17))
```

**Comment by etiennebacher** [comment]
Hello, I rarely use base plots in R, mostly because I don't find it very convenient so thank you for this package!

It looks like in `plot.default()`, the argument `log` is passed to `plot.window()` (which then uses some internal C code), so isn't it enough to pass this argument to `plot.window()` in `plot2()`? Or am I missing something?

I can try a PR for this if you want

**Comment by grantmcdermott** [comment]
> so isn't it enough to pass this argument to plot.window() in plot2()

It could well be... I just never got around to trying or testing. A PR would be very welcome!
